In [1]:
import pandas as pd

In [4]:
crime_df = pd.read_csv('../../data/crime_type_by_year_cleaned.csv', index_col=0)
crime_df

,Territory_Code,Territory_Name,REATIPS_VICES,Crime_Type,Year,Number_of_Crime
0,IT,Italy,MASSMURD,mass murder,2017-01-01,17
1,IT,Italy,MASSMURD,mass murder,2018-01-01,20
2,IT,Italy,MASSMURD,mass murder,2019-01-01,14
3,IT,Italy,MASSMURD,mass murder,2020-01-01,29
4,IT,Italy,MASSMURD,mass murder,2021-01-01,29
...,...,...,...,...,...,...
36979,ITG12,Palermo,USURY,usury,2017-01-01,6
36980,ITG12,Palermo,USURY,usury,2018-01-01,5
36981,ITG12,Palermo,USURY,usury,2019-01-01,6
36982,ITG12,Palermo,USURY,usury,2020-01-01,8
36983,ITG12,Palermo,USURY,usury,2021-01-01,2

In [7]:
# unique count in Territory_Name
crime_df['Year'].unique()

array(['2017-01-01', '2018-01-01', '2019-01-01', '2020-01-01',
       '2021-01-01'], dtype=object)

In [8]:
# on Year column remove string after -
crime_df['Year'] = crime_df['Year'].str.split('-').str[0]
crime_df['Year'].unique()

array(['2017', '2018', '2019', '2020', '2021'], dtype=object)

In [9]:
# save to csv
crime_df.to_csv('../../data/crime_type_by_year_cleaned.csv')

In [10]:
NUTS_df = pd.read_csv('../../data/NUTS_Code_Processed.csv', index_col=0)
NUTS_df

,Code_1,NUTS_2,Code_2,NUTS_3,Code_3,NUTS_2_Images,NUTS_3_Images
NUTS_1,,,,,,,
Northwest Italy,ITC,Piemonte,ITC1,Torino,ITC11,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...
Northwest Italy,ITC,Piemonte,ITC1,Vercelli,ITC12,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...
Northwest Italy,ITC,Piemonte,ITC1,Biella,ITC13,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...
Northwest Italy,ITC,Lombardia,ITC4,Varese,ITC41,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...
Northwest Italy,ITC,Lombardia,ITC4,Pavia,ITC48,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...
...,...,...,...,...,...,...,...
Central Italy,ITI,Lazio,ITI4,Viterbo,ITI41,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...
Central Italy,ITI,Lazio,ITI4,Rieti,ITI42,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...
Central Italy,ITI,Lazio,ITI4,Roma,ITI43,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...
Central Italy,ITI,Lazio,ITI4,Latina,ITI44,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...
Central Italy,ITI,Lazio,ITI4,Frosinone,ITI45,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...